### ISSUE TITLE
Breaking Changes & Deprecations

### ISSUE THREAD

**Issue by gaetanosestito** [londonappbrewery/Flash-Chat-Flutter-Complete#10]
Hey all,
Firebase's API for flutter has changed the way developers integrate Flutter applications with Firebase. So exist a migration guide to help with updating existing and new projects for Flash chat.
Please check it out: [Migration Guide](https://firebase.flutter.dev/docs/migration)

About me, I had to do a call to `Firebase.initializeApp();`  in order  to run successuful.

**Comment by mohitnakum** [comment]
also change **before:FirebaseUser** loggedInUser; **after:User** loggedInUser; because FierbaseUser Deprecated 
and currentUser now synchronize  so  not needed async.
Accessing the current user via currentUser() is now synchronous via the currentUser getter.
https://firebase.flutter.dev/docs/migration/

**Comment by dryusha** [comment]
Yeah..
I change my main() function into main.dart file like dat 
__________________________
....
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(FlashChat());
}
....
__________________________

and second changes its import firebase auth and deprecated FirebaseUser change to auth.User
example for chat screen.

__________________________
import 'package:firebase_auth/firebase_auth.dart' as auth; 
...
auth.User loggedInUser;

  @override
  void initState() {
    super.initState();

    getCurrentUser();
  }

  void getCurrentUser() {
    try {
      final user = _auth.currentUser;
      if (user != null) {
        loggedInUser = user;
        print(loggedInUser.email);
      }
    } catch (e) {
      print(e);
    }
  }
...
__________________________

Lesson N18-19.
Also Firestore is deprecated need to used FirebaseFirestore,
final _fireStore = FirebaseFirestore.instance;
if u are using streams, snapshot.documents is deprecated too and need to call snapshot.docs with responses data func.
__________________________
void getMessages() async {
    await for (var snapshot in _fireStore.collection('messages').snapshots()) {
      for (var message in snapshot.docs) {
        print(message.data());
      }
    }
  }
__________________________

**Comment by digitpk** [comment]
Also, guide the latest code regarding stream builder (L#21. Turning Streams into Widgets Using the StreamBuilder) as I didn't get the expected results.

mine code is: 
StreamBuilder<QuerySnapshot>(
              stream: _firestore.collection('messages').snapshots(),
              builder: (context, snapshot) {
                if (snapshot.hasData) {
                  final messages = snapshot.data.docs;
                  List<Text> messageWidgets = [];
                  for (var message in messages) {

// i get the error here on the parenthesis
final messageText = message.data();
final messageSender = message.data();

                    final messageWidget =
                        Text('$messageText from $messageSender');
                    messageWidgets.add(messageWidget);
                  }
                }
              },
            ),

**Comment by digitpk** [comment]
Also, guide the latest code regarding stream builder (L#21. Turning Streams into Widgets Using the StreamBuilder) as I didn't get the expected results.

mine code is:
`StreamBuilder<QuerySnapshot>(
              stream: _firestore.collection('messages').snapshots(),
              builder: (context, snapshot) {
                if (snapshot.hasData) {
                  final messages = snapshot.data.docs;
                  List<Text> messageWidgets = [];
                  for (var message in messages) {
                    final messageText = message.data();
                    final messageSender = message.data();

                    final messageWidget =
                        Text('$messageText from $messageSender');
                    messageWidgets.add(messageWidget);
                  }
                }
              },
            ),`

**Comment by digitpk** [comment]
I got this error fix by using adding this:

// i get the error fix here by adding fields after the parenthesis
final messageText = message.data()['field 1'];
final messageSender = message.data()['field 2'];

**Comment by FredWolfe** [comment]
@digitpk 

this is how I fixed the buildstream  error


StreamBuilder<QuerySnapshot>(
              stream: _fireStore.collection('messages').snapshots(),
              builder: (context, snapshot) {
                if (snapshot.hasData) {}
                final messages = snapshot.data.docs;
                List<Text> messageWidgets = [];
                for (var message in messages) {
                  final messageText = message.data()['text'];
                  final messageSender = message.data()['sender'];

                  final messageWidget =
                      Text('$messageText from $messageSender');
                  messageWidgets.add(messageWidget);
                }
                return Column(
                  children: messageWidgets,
                );
              },
            ),

**Comment by sameer882000** [comment]
> @digitpk
> 
> this is how I fixed the buildstream error
> 
> StreamBuilder(
> stream: _fireStore.collection('messages').snapshots(),
> builder: (context, snapshot) {
> if (snapshot.hasData) {}
> final messages = snapshot.data.docs;
> List<Text> messageWidgets = [];
> for (var message in messages) {
> final messageText = message.data()['text'];
> final messageSender = message.data()['sender'];
> 
> ```
>               final messageWidget =
>                   Text('$messageText from $messageSender');
>               messageWidgets.add(messageWidget);
>             }
>             return Column(
>               children: messageWidgets,
>             );
>           },
>         ),
> ```

I was still getting the error of type List<dynamic> is not a subtype of type 'List<Widget>'.  
So add this in List<Text>

**Comment by gravitas-dev** [comment]
@FredWolfe 
Your solution bypasses the snapshot.hasdata check.

Here is my solution : 
`StreamBuilder<QuerySnapshot>(
              stream: _fireStore.collection('messages').snapshots(),
              builder: (context, snapshot) {
                if (snapshot.hasData) {
                  final messages = snapshot.data.docs;
                  List<Text> messageWidgets = [];
                  for (var message in messages) {
                    final messageText = message.data()['text'];
                    final messageSender = message.data()['sender'];

                    final messageWidget =
                        Text('$messageText from $messageSender');
                    messageWidgets.add(messageWidget);
                  }
                  return Column(
                    children: messageWidgets,
                  );
                } else {
                  return Column(
                    children: null,
                  );
                }
              },
            ),`

**Comment by steph9600** [comment]
final messageText = message.data()['text'];
final messageSender = message.data()['sender'];

isn't working for me. i get an error: The operator '[]' isn't defined for the type 'Object'. (undefined_operator at [flash_chat] lib\screens\chat_screen.dart:114)

Wondering if anybody has encountered this/has a fix

**Comment by LoneWolfPJT** [comment]
final messageText = message['text'];
final messageSender = message['sender'];

you can fix it

**Comment by steph9600** [comment]
worked like a charm. thanks!

**Comment by Caleb1920** [comment]
> final messageText = message['text'];
> final messageSender = message['sender'];
> 
> you can fix it

**Comment by noooobie** [comment]
```
StreamBuilder<QuerySnapshot>(
                stream: _firestore.collection('message').snapshots(),
                builder: (context, snapshot) {
                  if (snapshot.hasData) {
                    final messages = snapshot.data.docs;
                    List<Text> messageWidgets = [];
                    for (var message in messages) {
                      final messageText = message['text'];
                      final messageSender = message['sender'];

                      final messageWidget =
                          Text('$messageText from $messageSender');
                      messageWidget.add(messageWidget);
                    }
                    return Column(
                      children: messageWidgets,
                    );
                  }
                }),
```

i'm getting errors like
1. This function has a return type of 'Widget', but doesn't end with a return statement. (Documentation)  Try adding a return statement, or changing the return type to 'void'.
2. The method 'add' isn't defined for the type 'Text'. (Documentation)  Try correcting the name to the name of an existing method, or defining a method named 'add'.

What to do?

**Comment by dyardy** [comment]
This was final StreamBuilder returned from _firestore.collection('messages').snapshots(); Hope this helps someone.

```
StreamBuilder(
    stream: _firestore.collection('messages').snapshots(),
    builder: (BuildContext context,
        AsyncSnapshot<QuerySnapshot> snapshot) {
      if (snapshot.hasData) {
        final messages = snapshot.data?.docs;
        List<Text> messageWidgets = [];
        for (var message in messages!) {
          final messageText = message['text'];
          final messageSender = message['sender'];
          final messageWidget =
              Text('$messageText from $messageSender');

          messageWidgets.add(messageWidget);
        }
        return Column(
          children: messageWidgets,
        );
      }
      return Text('no data');
      // return Text('${snapshot.data}');
    }),
```

**Comment by Yougraj** [comment]
> This was final StreamBuilder returned from _firestore.collection('messages').snapshots(); Hope this helps someone.
> 
> ```
> StreamBuilder(
>     stream: _firestore.collection('messages').snapshots(),
>     builder: (BuildContext context,
>         AsyncSnapshot<QuerySnapshot> snapshot) {
>       if (snapshot.hasData) {
>         final messages = snapshot.data?.docs;
>         List<Text> messageWidgets = [];
>         for (var message in messages!) {
>           final messageText = message['text'];
>           final messageSender = message['sender'];
>           final messageWidget =
>               Text('$messageText from $messageSender');
> 
>           messageWidgets.add(messageWidget);
>         }
>         return Column(
>           children: messageWidgets,
>         );
>       }
>       return Text('no data');
>       // return Text('${snapshot.data}');
>     }),
> ```

thank you

**Comment by ravi238873** [comment]
> This was final StreamBuilder returned from _firestore.collection('messages').snapshots(); Hope this helps someone.
> 
> ```
> StreamBuilder(
>     stream: _firestore.collection('messages').snapshots(),
>     builder: (BuildContext context,
>         AsyncSnapshot<QuerySnapshot> snapshot) {
>       if (snapshot.hasData) {
>         final messages = snapshot.data?.docs;
>         List<Text> messageWidgets = [];
>         for (var message in messages!) {
>           final messageText = message['text'];
>           final messageSender = message['sender'];
>           final messageWidget =
>               Text('$messageText from $messageSender');
> 
>           messageWidgets.add(messageWidget);
>         }
>         return Column(
>           children: messageWidgets,
>         );
>       }
>       return Text('no data');
>       // return Text('${snapshot.data}');
>     }),
> ```



This works and consider this as final solution.

**Comment by FredWolfe** [comment]
> This was final StreamBuilder returned from _firestore.collection('messages').snapshots(); Hope this helps someone.
> 
> ```
> StreamBuilder(
>     stream: _firestore.collection('messages').snapshots(),
>     builder: (BuildContext context,
>         AsyncSnapshot<QuerySnapshot> snapshot) {
>       if (snapshot.hasData) {
>         final messages = snapshot.data?.docs;
>         List<Text> messageWidgets = [];
>         for (var message in messages!) {
>           final messageText = message['text'];
>           final messageSender = message['sender'];
>           final messageWidget =
>               Text('$messageText from $messageSender');
> 
>           messageWidgets.add(messageWidget);
>         }
>         return Column(
>           children: messageWidgets,
>         );
>       }
>       return Text('no data');
>       // return Text('${snapshot.data}');
>     }),
> ```

thanks so much
